const paragraphs = [
  "The early morning air carried a faint chill, but the promise of sunrise softened it. Birds began to fill the sky with their casual patterns, moving like thoughts that hadn’t yet formed into words. A shopkeeper raised the shutter of his small store, letting the light spill across the tiled floor. Down the road, a cyclist passed with quiet determination, the wheels slicing through the silence of dawn. Nothing remarkable seemed to happen, yet this quiet hour held a subtle importance. It was a reset, a moment when the day had not yet decided what it would become.",

  "The art of patience is not learned through comfort. It grows in the pauses between effort and reward. When progress feels invisible, patience teaches us to trust unseen motion. Every skill worth keeping demands small, repeated acts of faith. Whether it is playing an instrument, writing a line of code, or mastering a recipe, the pattern is the same. You fail, adjust, and try again. Patience is not waiting without movement; it is continuing to move while the result still hides beyond sight. In time, what once felt uncertain becomes second nature.",

  "Technology changes faster than habits. We adapt to new devices but rarely to new ways of thinking. The tools grow sharper, yet the purpose often blurs. It is easy to scroll endlessly and still feel behind. True understanding begins when we pause to ask what we are chasing. The screen offers endless options, but not meaning. Meaning is built, not streamed. It forms when attention meets intention, when the click has a reason beyond habit. Progress depends less on speed and more on awareness of direction.",

  "A good conversation can change the course of a day. Words, when chosen with care, carry more weight than we realize. Listening deeply is harder than speaking clearly, but it is the skill that builds trust. People often listen to respond, not to understand. Yet the quiet between sentences is where connection forms. Every friendship, every strong relationship, is built on the courage to hear before being heard. The best words come not from cleverness, but from calm attention.",

  "Rain began to fall softly, blurring the outlines of distant buildings. The street reflected each drop like liquid glass. A child ran barefoot through a puddle, laughing at nothing but the moment itself. Cars slowed, umbrellas opened, and for a brief time the city moved in rhythm with the rain. There was no hurry, no rush to escape the weather. Sometimes the simplest act — standing still while it rains — reminds us how rare it is to feel completely present, even for a second.",

  "The workspace was quiet except for the soft hum of a computer fan. A mug of coffee cooled beside a stack of notes, each one scribbled with plans and corrections. The project had taken longer than expected, but something about the slow progress felt right. The small victories — fixing a bug, rewriting a sentence, refining a design — built a steady rhythm of focus. It wasn’t perfection that mattered, but persistence. Every small step was a reminder that improvement is built one detail at a time.",

  "In the middle of the city stood a park that seemed immune to noise. The wind carried the scent of cut grass, and somewhere a musician played quietly under a tree. Strangers crossed paths, shared glances, then went on without words. It was an ordinary scene, but something about its stillness made time stretch. People need such pauses — moments where doing nothing feels natural. The park was not an escape from life but a mirror of it, slowed just enough to notice the details.",

  "Every challenge begins with uncertainty. The first step into the unknown rarely feels confident. But uncertainty is not failure; it is proof that we are learning something real. When the outcome is obvious, no growth occurs. Each mistake marks the edge of what we know. Courage is not the absence of doubt but movement despite it. Over time, what once felt difficult becomes familiar, and fear gives way to quiet strength. Growth is not a straight path, but it is always forward.",

  "Music has a way of describing feelings that words cannot reach. A melody can pull old memories to the surface or soften a hard mood in seconds. Even a single note can remind someone of home, of loss, or of peace. Musicians speak through vibration and timing, and listeners translate it into emotion. It is a conversation without language. In every performance, there is a trace of both the player and the listener — a silent understanding that beauty doesn’t need to explain itself.",

  "Books remain one of humanity’s quietest miracles. A page written decades ago can still speak directly to a stranger today. Through them, voices outlive their bodies, and experiences cross centuries without fading. Reading slows the world just enough to think deeply. In the pause between paragraphs, the mind stretches and connects ideas that speech might overlook. No matter how technology evolves, the printed word will always offer something digital noise cannot — stillness that teaches.",

  "Distraction is the easiest habit to build and the hardest to break. It begins with one quick glance at a notification and ends with hours lost to nothing in particular. Attention is a finite resource, quietly traded every day. Regaining it requires deliberate effort: turning off alerts, setting boundaries, choosing moments of silence. Focus is not about control but clarity — deciding what deserves your presence. Every minute reclaimed from distraction is a small act of freedom.",

  "Travel changes how we see the world, not just geographically but emotionally. Stepping into unfamiliar streets resets our sense of scale and expectation. We notice how other people live, how they greet, how they rest. The experience teaches humility and curiosity. The more we travel, the more we realize that cultures differ in style, not in longing. Everyone wants peace, belonging, and purpose. Returning home, we see familiar places with new eyes — not smaller, but richer.",

  "Failure is an underrated teacher. It cuts through pride and forces honesty. While success decorates the surface, failure shapes the foundation. It reveals what works, what doesn’t, and who truly cares to continue. The fear of failing often blocks action more than failure itself ever could. Learning to fail well — with reflection, not regret — is a skill that keeps progress alive. Those who master it eventually discover that resilience, not talent, defines long-term success.",

  "The ocean never repeats itself. Every wave forms, rises, and falls in a pattern that will never occur again. Yet the sound of it feels timeless. Standing near the water reminds us how small and temporary we are, yet how connected to everything. The tide comes and goes without permission or pause, a rhythm older than memory. Watching it for even a few minutes resets the noise in the mind. Nature speaks quietly, but it always says enough.",

  "Evening brings a kind of reflection that daylight doesn’t allow. As the sky shifts from blue to violet, thoughts slow down. The day’s noise softens, leaving space for small realizations — tasks completed, words unsaid, plans deferred. The glow of streetlights feels like punctuation marks between moments. Night doesn’t demand much; it invites pause. In that pause, gratitude often appears, gentle and unannounced, reminding us that being here, still breathing, is already enough."
];
